defmodule MyAppWeb.Integration.AdminTest do
  @moduledoc """
  Smoke tests for the authenticated admin LiveView surface.

  Uses `Ash.Seed.seed!/2` to plant a user record directly, then puts
  the actor in the session via ash_authentication's session helper.
  This bypasses the configured login strategy (password / magic_link /
  …) so the test is strategy-agnostic.

  Generated by `mix soot.gen.phoenix_test`. Operators own this file.
  """

  use MyAppWeb.ConnCase, async: true

  import PhoenixTest

  @moduletag :phoenix_test

  setup %{conn: conn} do
    email = "phoenix-test-#{System.unique_integer([:positive])}@example.com"

    user =
      Ash.Seed.seed!(MyApp.Accounts.User, %{
        email: email,
        confirmed_at: DateTime.utc_now()
      })

    conn =
      conn
      |> Plug.Test.init_test_session(%{})
      |> AshAuthentication.Plug.Helpers.store_in_session(user)

    {:ok, conn: conn, user: user}
  end

  test "GET /admin renders the overview", %{conn: conn} do
    conn
    |> visit("/admin")
    |> assert_has("nav", text: "Soot Admin")
  end

  test "GET /admin/devices renders the device tab", %{conn: conn} do
    conn
    |> visit("/admin/devices")
    |> assert_has("nav", text: "Soot Admin")
  end
end
