defmodule MyAppWeb.Integration.AuthTest do
  @moduledoc """
  Smoke tests for the auth surface. Verifies that the sign-in route is
  mounted and that unauthenticated visits to `/admin` are redirected.

  Independent of the configured ash_authentication strategy: only
  asserts on the presence of the sign-in form, not on its specific
  fields (which differ between password and magic_link).

  Generated by `mix soot.gen.phoenix_test`. Operators own this file.
  """

  use MyAppWeb.ConnCase, async: true

  import PhoenixTest

  @moduletag :phoenix_test

  test "GET /sign-in renders an auth form", %{conn: conn} do
    conn
    |> visit("/sign-in")
    |> assert_has("form")
  end

  test "GET /admin redirects to sign-in when unauthenticated", %{conn: conn} do
    # Phoenix_test follows the redirect chain by default; landing on
    # `/sign-in` (or any auth-required route that renders the sign-in
    # form) is the contract. We assert on the form rather than the
    # exact path to stay strategy-agnostic.
    conn
    |> visit("/admin")
    |> assert_has("form")
  end
end
