defmodule MyAppWeb.Integration.HomeTest do
  @moduledoc """
  Smoke test for the unauthenticated landing page.

  Generated by `mix soot.gen.phoenix_test`. Operators own this file;
  re-running the generator will not overwrite it.
  """

  use MyAppWeb.ConnCase, async: true

  import PhoenixTest

  @moduletag :phoenix_test

  test "GET / renders without an authenticated user", %{conn: conn} do
    conn
    |> visit("/")
    |> assert_has("body")
  end
end
