defmodule Soot.MixTasksTest do
  use ExUnit.Case, async: false

  @tmp Path.join(System.tmp_dir!(), "soot_mix_tasks_test")

  setup do
    File.rm_rf!(@tmp)
    File.mkdir_p!(@tmp)
    on_exit(fn -> File.rm_rf!(@tmp) end)
    :ok
  end

  describe "mix soot.new" do
    test "errors out without an app name" do
      assert_raise Mix.Error, ~r/Usage/, fn ->
        Mix.Tasks.Soot.New.run([])
      end
    end

    test "scaffolds the expected files into a fresh dir" do
      target = Path.join(@tmp, "my_iot")

      capture_io(fn ->
        Mix.Tasks.Soot.New.run(["my_iot", "--into", target])
      end)

      assert File.read!(Path.join(target, "mix.exs")) =~ "defmodule MyIot.MixProject"
      assert File.read!(Path.join(target, "lib/my_iot/application.ex")) =~ "MyIot.Application"
      assert File.read!(Path.join(target, "lib/my_iot/endpoint.ex")) =~ "AshPki.Plug.MTLS"
      assert File.read!(Path.join(target, "lib/my_iot/endpoint.ex")) =~ "SootCore.Plug.Enroll"

      assert File.read!(Path.join(target, "README.md")) =~ "Generated by `mix soot.new my_iot`"
    end

    test "honours --module override" do
      target = Path.join(@tmp, "weird_dir_name")

      capture_io(fn ->
        Mix.Tasks.Soot.New.run([
          "weird_dir_name",
          "--into",
          target,
          "--module",
          "Acme.IoT"
        ])
      end)

      assert File.read!(Path.join(target, "mix.exs")) =~ "defmodule Acme.IoT.MixProject"
    end

    test "skips existing files unless --force" do
      target = Path.join(@tmp, "exists")
      File.mkdir_p!(target)
      File.write!(Path.join(target, "mix.exs"), "preserved\n")

      output =
        capture_io(fn ->
          Mix.Tasks.Soot.New.run(["exists", "--into", target])
        end)

      assert File.read!(Path.join(target, "mix.exs")) == "preserved\n"
      assert output =~ "skip"

      capture_io(fn ->
        Mix.Tasks.Soot.New.run(["exists", "--into", target, "--force"])
      end)

      refute File.read!(Path.join(target, "mix.exs")) == "preserved\n"
    end
  end

  describe "mix soot.broker.gen_config" do
    test "writes both files by default" do
      out = Path.join(@tmp, "broker")

      capture_io(fn ->
        Mix.Tasks.Soot.Broker.GenConfig.run([
          "--out",
          out,
          "--resource",
          "Soot.Test.Fixtures.Device"
        ])
      end)

      assert File.exists?(Path.join(out, "mosquitto.acl"))
      assert File.exists?(Path.join(out, "mosquitto.conf"))
      assert File.exists?(Path.join(out, "emqx.json"))

      assert File.read!(Path.join(out, "mosquitto.acl")) =~ "tenants/%u/devices/%c/up"

      assert {:ok, %{"acl" => _, "rules" => _}} =
               Jason.decode(File.read!(Path.join(out, "emqx.json")))
    end

    test "--mosquitto-only skips emqx.json" do
      out = Path.join(@tmp, "broker_mosq")

      capture_io(fn ->
        Mix.Tasks.Soot.Broker.GenConfig.run([
          "--out",
          out,
          "--mosquitto-only",
          "--resource",
          "Soot.Test.Fixtures.Device"
        ])
      end)

      assert File.exists?(Path.join(out, "mosquitto.acl"))
      refute File.exists?(Path.join(out, "emqx.json"))
    end

    test "--emqx-only skips mosquitto" do
      out = Path.join(@tmp, "broker_emqx")

      capture_io(fn ->
        Mix.Tasks.Soot.Broker.GenConfig.run([
          "--out",
          out,
          "--emqx-only",
          "--resource",
          "Soot.Test.Fixtures.Device"
        ])
      end)

      refute File.exists?(Path.join(out, "mosquitto.acl"))
      refute File.exists?(Path.join(out, "mosquitto.conf"))
      assert File.exists?(Path.join(out, "emqx.json"))
    end

    test "errors out without --resource" do
      assert_raise Mix.Error, fn ->
        capture_io(fn ->
          Mix.Tasks.Soot.Broker.GenConfig.run(["--out", Path.join(@tmp, "x")])
        end)
      end
    end

    test "rejects --mosquitto-only and --emqx-only together" do
      assert_raise Mix.Error, fn ->
        capture_io(fn ->
          Mix.Tasks.Soot.Broker.GenConfig.run([
            "--out",
            Path.join(@tmp, "y"),
            "--mosquitto-only",
            "--emqx-only",
            "--resource",
            "Soot.Test.Fixtures.Device"
          ])
        end)
      end
    end
  end

  defp capture_io(fun), do: ExUnit.CaptureIO.capture_io(fun)
end
