defmodule Soot.MixTasksTest do
  use ExUnit.Case, async: false

  @tmp Path.join(System.tmp_dir!(), "soot_mix_tasks_test")

  setup do
    File.rm_rf!(@tmp)
    File.mkdir_p!(@tmp)
    on_exit(fn -> File.rm_rf!(@tmp) end)
    :ok
  end

  describe "mix soot.new" do
    test "errors out without an app name" do
      assert_raise Mix.Error, ~r/Usage/, fn ->
        Mix.Tasks.Soot.New.run([])
      end
    end

    test "scaffolds the expected files into a fresh dir" do
      target = Path.join(@tmp, "my_iot")

      capture_io(fn ->
        Mix.Tasks.Soot.New.run(["my_iot", "--into", target])
      end)

      assert File.read!(Path.join(target, "mix.exs")) =~ "defmodule MyIot.MixProject"
      assert File.read!(Path.join(target, "lib/my_iot/application.ex")) =~ "MyIot.Application"
      assert File.read!(Path.join(target, "lib/my_iot/endpoint.ex")) =~ "AshPki.Plug.MTLS"
      assert File.read!(Path.join(target, "lib/my_iot/endpoint.ex")) =~ "SootCore.Plug.Enroll"

      assert File.read!(Path.join(target, "README.md")) =~ "Generated by `mix soot.new my_iot`"
    end

    test "honours --module override" do
      target = Path.join(@tmp, "weird_dir_name")

      capture_io(fn ->
        Mix.Tasks.Soot.New.run([
          "weird_dir_name",
          "--into",
          target,
          "--module",
          "Acme.IoT"
        ])
      end)

      assert File.read!(Path.join(target, "mix.exs")) =~ "defmodule Acme.IoT.MixProject"
    end

    test "rejects an invalid --module name" do
      assert_raise Mix.Error, ~r/invalid module name/, fn ->
        Mix.Tasks.Soot.New.run([
          "weird",
          "--into",
          Path.join(@tmp, "weird"),
          "--module",
          "1Foo"
        ])
      end

      assert_raise Mix.Error, ~r/invalid module name/, fn ->
        Mix.Tasks.Soot.New.run([
          "weird",
          "--into",
          Path.join(@tmp, "weird2"),
          "--module",
          "lower_case"
        ])
      end
    end

    test "the rendered mix.exs parses as valid Elixir with the expected children" do
      target = Path.join(@tmp, "parse_check")

      capture_io(fn ->
        Mix.Tasks.Soot.New.run(["parse_check", "--into", target])
      end)

      mix_exs = File.read!(Path.join(target, "mix.exs"))

      # Must parse without error.
      ast = Code.string_to_quoted!(mix_exs)
      assert match?({:defmodule, _, _}, ast)

      # Sanity-check that the deps list is path: (bug 1) and not the
      # not-yet-published hex requirements that would break `mix deps.get`.
      assert mix_exs =~ ~s({:ash_pki, path: "../ash_pki"})
      refute mix_exs =~ ~s({:ash_pki, "~>)

      # Other generated files exist.
      assert File.exists?(Path.join(target, ".tool-versions"))
      assert File.exists?(Path.join(target, "lib/parse_check.ex"))

      # And lib/<app>.ex parses too.
      app_ex = File.read!(Path.join(target, "lib/parse_check.ex"))
      assert match?({:defmodule, _, _}, Code.string_to_quoted!(app_ex))
    end

    test "skips existing files unless --force" do
      target = Path.join(@tmp, "exists")
      File.mkdir_p!(target)
      File.write!(Path.join(target, "mix.exs"), "preserved\n")

      output =
        capture_io(fn ->
          Mix.Tasks.Soot.New.run(["exists", "--into", target])
        end)

      assert File.read!(Path.join(target, "mix.exs")) == "preserved\n"
      assert output =~ "skip"

      capture_io(fn ->
        Mix.Tasks.Soot.New.run(["exists", "--into", target, "--force"])
      end)

      refute File.read!(Path.join(target, "mix.exs")) == "preserved\n"
    end
  end

  describe "mix soot.broker.gen_config" do
    test "writes both files by default" do
      out = Path.join(@tmp, "broker")

      capture_io(fn ->
        Mix.Tasks.Soot.Broker.GenConfig.run([
          "--out",
          out,
          "--resource",
          "Soot.Test.Fixtures.Device"
        ])
      end)

      assert File.exists?(Path.join(out, "mosquitto.acl"))
      assert File.exists?(Path.join(out, "mosquitto.conf"))
      assert File.exists?(Path.join(out, "emqx.json"))

      assert File.read!(Path.join(out, "mosquitto.acl")) =~ "tenants/%u/devices/%c/up"

      assert {:ok, %{"acl" => _, "rules" => _}} =
               Jason.decode(File.read!(Path.join(out, "emqx.json")))
    end

    test "--mosquitto-only skips emqx.json" do
      out = Path.join(@tmp, "broker_mosq")

      capture_io(fn ->
        Mix.Tasks.Soot.Broker.GenConfig.run([
          "--out",
          out,
          "--mosquitto-only",
          "--resource",
          "Soot.Test.Fixtures.Device"
        ])
      end)

      assert File.exists?(Path.join(out, "mosquitto.acl"))
      refute File.exists?(Path.join(out, "emqx.json"))
    end

    test "--emqx-only skips mosquitto" do
      out = Path.join(@tmp, "broker_emqx")

      capture_io(fn ->
        Mix.Tasks.Soot.Broker.GenConfig.run([
          "--out",
          out,
          "--emqx-only",
          "--resource",
          "Soot.Test.Fixtures.Device"
        ])
      end)

      refute File.exists?(Path.join(out, "mosquitto.acl"))
      refute File.exists?(Path.join(out, "mosquitto.conf"))
      assert File.exists?(Path.join(out, "emqx.json"))
    end

    test "errors out without --resource" do
      assert_raise Mix.Error, fn ->
        capture_io(fn ->
          Mix.Tasks.Soot.Broker.GenConfig.run(["--out", Path.join(@tmp, "x")])
        end)
      end
    end

    test "rejects --mosquitto-only and --emqx-only together" do
      assert_raise Mix.Error, fn ->
        capture_io(fn ->
          Mix.Tasks.Soot.Broker.GenConfig.run([
            "--out",
            Path.join(@tmp, "y"),
            "--mosquitto-only",
            "--emqx-only",
            "--resource",
            "Soot.Test.Fixtures.Device"
          ])
        end)
      end
    end

    test "raises when --mosquitto-template points at a non-existent file" do
      out = Path.join(@tmp, "broker_missing_tpl")
      missing = Path.join(@tmp, "no_such_template.eex")

      assert_raise Mix.Error, ~r/--mosquitto-template/, fn ->
        capture_io(fn ->
          Mix.Tasks.Soot.Broker.GenConfig.run([
            "--out",
            out,
            "--mosquitto-template",
            missing,
            "--resource",
            "Soot.Test.Fixtures.Device"
          ])
        end)
      end
    end

    test "substitutes --ca-file/--cert-file/--key-file into mosquitto.conf" do
      out = Path.join(@tmp, "broker_paths")

      capture_io(fn ->
        Mix.Tasks.Soot.Broker.GenConfig.run([
          "--out",
          out,
          "--mosquitto-only",
          "--ca-file",
          "/tmp/example/ca.pem",
          "--cert-file",
          "/tmp/example/server_chain.pem",
          "--key-file",
          "/tmp/example/server_key.pem",
          "--persistence-dir",
          "/tmp/example/mosq-data",
          "--resource",
          "Soot.Test.Fixtures.Device"
        ])
      end)

      conf = File.read!(Path.join(out, "mosquitto.conf"))
      assert conf =~ "cafile /tmp/example/ca.pem"
      assert conf =~ "certfile /tmp/example/server_chain.pem"
      assert conf =~ "keyfile /tmp/example/server_key.pem"
      assert conf =~ "persistence_location /tmp/example/mosq-data"
    end
  end

  defp capture_io(fun), do: ExUnit.CaptureIO.capture_io(fun)
end
